Repository qarmin/czkawka, pull requests merged in 2020-10, with the labels that each got.

#29 Switch to automatic updates for the program version.
  czkawka_core/src/lib.rs
Labels: enhancement

#39 Add storing artifacts in CI
  .github/workflows/ci.yml
Labels: enhancement

#36 Arch PKGBUILD
  pkgs/arch/.SRCINFO
  pkgs/arch/.gitignore
  pkgs/arch/PKGBUILD
  pkgs/arch/com.github.qarmin.czkawka.desktop
  pkgs/com.github.qarmin.czkawka.desktop
Labels: enhancement

#37 Changed to StructOpt for CLI argument parser.
  Cargo.lock
  czkawka_cli/Cargo.toml
  czkawka_cli/src/arguments_pair.rs
  czkawka_cli/src/commands.rs
  czkawka_cli/src/main.rs
Labels: enhancement

#41 Test Windows GUI cross-build in CI
  .github/workflows/ci.yml
Labels: enhancement

#48 Divide CI across multiple files
  .github/workflows/ci.yml
  .github/workflows/linux.yml
  .github/workflows/mac.yml
  .github/workflows/quality.yml
  .github/workflows/windows.yml
Labels: enhancement

#51 Add support for searching in other thread
  czkawka_core/src/duplicate.rs
  czkawka_gui/src/help_functions.rs
  czkawka_gui/src/main.rs
Labels: enhancement

#52 Improve code quality.
  czkawka_core/src/big_file.rs
  czkawka_core/src/common.rs
  czkawka_core/src/common_directory.rs
  czkawka_core/src/common_extensions.rs
  czkawka_core/src/common_items.rs
  czkawka_core/src/common_messages.rs
  czkawka_core/src/duplicate.rs
  czkawka_core/src/empty_files.rs
  czkawka_core/src/empty_folder.rs
  czkawka_core/src/temporary.rs
  czkawka_gui/src/main.rs
Labels: enhancement

#55 Add ability to stop task from GUI
  Cargo.lock
  Changelog.md
  czkawka_cli/Cargo.toml
  czkawka_cli/src/main.rs
  czkawka_core/Cargo.toml
  czkawka_core/src/big_file.rs
  czkawka_core/src/common.rs
  czkawka_core/src/duplicate.rs
  czkawka_core/src/empty_files.rs
  czkawka_core/src/empty_folder.rs
  czkawka_core/src/temporary.rs
  czkawka_gui/Cargo.toml
  czkawka_gui/src/help_functions.rs
  czkawka_gui/src/main.rs
  czkawka_gui_orbtk/Cargo.toml
Labels: bug, enhancement

#57 Fix not removing from GUI empty folders which contains another empty folder
  czkawka_gui/src/main.rs
Labels: bug

#58 Add windows support
  czkawka_core/src/big_file.rs
  czkawka_core/src/common.rs
  czkawka_core/src/common_directory.rs
  czkawka_core/src/duplicate.rs
  czkawka_core/src/empty_files.rs
  czkawka_core/src/empty_folder.rs
  czkawka_core/src/temporary.rs
Labels: enhancement

#65 Add test suite for automatically checking for regressions
  .github/workflows/linux.yml
  .github/workflows/windows.yml
  .gitignore
  Changelog.md
  misc/check_results.py
Labels: enhancement

#59 Replace String with PathBuf for paths
  czkawka_core/src/big_file.rs
  czkawka_core/src/common.rs
  czkawka_core/src/common_directory.rs
  czkawka_core/src/common_items.rs
  czkawka_core/src/duplicate.rs
  czkawka_core/src/empty_files.rs
  czkawka_core/src/empty_folder.rs
  czkawka_core/src/temporary.rs
  czkawka_gui/src/main.rs
Labels: bug, enhancement

#66 Add support to CLI tool for finding similar images
  Cargo.lock
  czkawka_cli/src/commands.rs
  czkawka_cli/src/main.rs
  czkawka_core/Cargo.toml
  czkawka_core/src/big_file.rs
  czkawka_core/src/lib.rs
  czkawka_core/src/similar_files.rs
  czkawka_gui/Cargo.toml
Labels: enhancement

#69 Add similar images support for GUI
  Changelog.md
  Instruction.md
  README.md
  czkawka_core/src/similar_files.rs
  czkawka_gui/czkawka.glade
  czkawka_gui/src/help_functions.rs
  czkawka_gui/src/main.rs
Labels: enhancement

#70 Added support for opening files by double clicks
  czkawka_gui/src/double_click_opening.rs
  czkawka_gui/src/main.rs
Labels: enhancement

#73 Improve similar images GUI a little and add sorting to Similarity Enum
  czkawka_core/src/similar_files.rs
  czkawka_gui/src/create_tree_view.rs
  czkawka_gui/src/help_functions.rs
  czkawka_gui/src/main.rs
Labels: enhancement

#75 Improve deleting files in Similar files in GUI
  czkawka_gui/src/main.rs
Labels: bug

#77 Add appimage support
  .github/workflows/linux.yml
  icon.png
  icon.svg
  pkgs/com.github.qarmin.czkawka.desktop
Labels: enhancement

#79 Remove warnings about non existent directories in Windows
  czkawka_core/src/common_directory.rs
  czkawka_gui/src/main.rs
Labels: enhancement

#83 Add pre hash check
  czkawka_core/src/duplicate.rs
  czkawka_gui/src/main.rs
Labels: enhancement

#84 Add support for checking for same file names
  README.md
  czkawka_cli/src/commands.rs
  czkawka_core/src/duplicate.rs
  czkawka_gui/czkawka.glade
  czkawka_gui/src/main.rs
  misc/.idea/workspace.xml
Labels: enhancement

#88 Add support for checking for zeroed files
  README.md
  czkawka_cli/src/commands.rs
  czkawka_cli/src/main.rs
  czkawka_core/src/lib.rs
  czkawka_core/src/zeroed.rs
  czkawka_gui/czkawka.glade
  czkawka_gui/src/create_tree_view.rs
  czkawka_gui/src/double_click_opening.rs
  czkawka_gui/src/help_functions.rs
  czkawka_gui/src/main.rs
Labels: enhancement

#89 Refactor GUI into multiple files
  czkawka_gui/src/connect_button_delete.rs
  czkawka_gui/src/connect_button_save.rs
  czkawka_gui/src/connect_button_search.rs
  czkawka_gui/src/connect_button_select.rs
  czkawka_gui/src/connect_button_stop.rs
  czkawka_gui/src/connect_compute_results.rs
  czkawka_gui/src/connect_notebook_tabs.rs
  czkawka_gui/src/connect_popover_duplicate.rs
  czkawka_gui/src/connect_upper_notebook.rs
  czkawka_gui/src/gui_data.rs
  czkawka_gui/src/help_functions.rs
  czkawka_gui/src/main.rs
  czkawka_gui/src/startup_configuration.rs
Labels: enhancement

#90 Add missing options in some modes
  czkawka_cli/src/commands.rs
  czkawka_cli/src/main.rs
  czkawka_core/src/big_file.rs
  czkawka_core/src/empty_folder.rs
Labels: bug, enhancement
