Repository qarmin/czkawka, pull requests merged in 2021-03, with the labels that each got.

#277 Dryrun for duplicates
  czkawka_cli/src/commands.rs
  czkawka_cli/src/main.rs
  czkawka_core/src/duplicate.rs
Labels: enhancement

#263 Add option to turn off cache
  czkawka_core/src/broken_files.rs
  czkawka_core/src/duplicate.rs
  czkawka_core/src/similar_images.rs
  czkawka_gui/czkawka.glade
  czkawka_gui/src/connect_button_search.rs
  czkawka_gui/src/gui_settings.rs
  czkawka_gui/src/saving_loading.rs
Labels: enhancement

#281 Add confirmation dialog when trying to remove all files in group
  czkawka_gui/czkawka.glade
  czkawka_gui/src/connect_button_delete.rs
  czkawka_gui/src/gui_settings.rs
  czkawka_gui/src/saving_loading.rs
Labels: enhancement

#282 Add confirmation dialog when removing files with delete key
  czkawka_gui/czkawka.glade
  czkawka_gui/src/connect_button_delete.rs
  czkawka_gui/src/connect_button_stop.rs
  czkawka_gui/src/initialize_gui.rs
Labels: bug, enhancement

#283 Use xxhash-rust >=0.8.2 to avoid bug in stateful implementation
  czkawka_core/Cargo.toml
Labels: bug

#285 Open file when clicking at the Enter button
  czkawka_gui/src/double_click_opening.rs
  czkawka_gui/src/initialize_gui.rs
Labels: enhancement

#284 Allow to put files to trash instead fully remove them
  Cargo.lock
  czkawka_gui/Cargo.toml
  czkawka_gui/czkawka.glade
  czkawka_gui/src/connect_button_delete.rs
  czkawka_gui/src/gui_settings.rs
  czkawka_gui/src/saving_loading.rs
Labels: enhancement

#302 Update to Rust 1.51
  Cargo.lock
  czkawka_cli/src/commands.rs
  czkawka_core/src/broken_files.rs
  czkawka_core/src/duplicate.rs
  czkawka_core/src/empty_folder.rs
  czkawka_core/src/similar_images.rs
  czkawka_gui/src/connect_button_search.rs
  czkawka_gui/src/connect_compute_results.rs
  czkawka_gui/src/connect_popovers.rs
  czkawka_gui/src/connect_progress_window.rs
  czkawka_gui/src/gui_about.rs
  czkawka_gui/src/gui_bottom_buttons.rs
  czkawka_gui/src/gui_data.rs
  czkawka_gui/src/gui_header.rs
  czkawka_gui/src/gui_main_notebook.rs
  czkawka_gui/src/gui_popovers.rs
  czkawka_gui/src/gui_progress_dialog.rs
  czkawka_gui/src/gui_settings.rs
  czkawka_gui/src/gui_upper_notepad.rs
  czkawka_gui/src/saving_loading.rs
  czkawka_gui/src/taskbar_progress_dummy.rs
Labels: enhancement
