Repository qarmin/czkawka, pull requests merged in 2021-12, with the labels that each got.

#474 More GTK 4 related changes
  czkawka_gui/src/connect_button_delete.rs
  czkawka_gui/src/connect_button_hardlink.rs
  czkawka_gui/src/connect_button_move.rs
  czkawka_gui/src/connect_button_search.rs
  czkawka_gui/src/connect_button_select.rs
  czkawka_gui/src/connect_button_stop.rs
  czkawka_gui/src/connect_header_buttons.rs
  czkawka_gui/src/connect_popovers.rs
  czkawka_gui/src/connect_selection_of_directories.rs
  czkawka_gui/src/connect_settings.rs
  czkawka_gui/src/connect_similar_image_size_change.rs
  czkawka_gui/src/gui_about.rs
  czkawka_gui/src/gui_bottom_buttons.rs
  czkawka_gui/src/gui_data.rs
  czkawka_gui/src/gui_main_notebook.rs
  czkawka_gui/src/gui_progress_dialog.rs
  czkawka_gui/src/help_functions.rs
  czkawka_gui/src/initialize_gui.rs
  czkawka_gui/ui/main_window.glade
Labels: enhancement

#476 Remove HashMB mode
  czkawka_cli/src/commands.rs
  czkawka_core/src/duplicate.rs
  czkawka_gui/src/compute_results.rs
  czkawka_gui/src/connect_button_search.rs
  czkawka_gui/src/connect_duplicate_buttons.rs
  czkawka_gui/src/connect_progress_window.rs
  czkawka_gui/src/connect_settings.rs
  czkawka_gui/src/gui_main_notebook.rs
  czkawka_gui/src/main.rs
  czkawka_gui/ui/main_window.glade
Labels: enhancement

#477 Add prehash cache support
  czkawka_cli/src/commands.rs
  czkawka_core/src/duplicate.rs
  czkawka_core/src/similar_videos.rs
  czkawka_gui/src/connect_button_search.rs
  czkawka_gui/src/connect_button_select.rs
  czkawka_gui/src/connect_popovers.rs
  czkawka_gui/src/gui_settings.rs
  czkawka_gui/src/help_functions.rs
  czkawka_gui/src/saving_loading.rs
  czkawka_gui/ui/settings.glade
Labels: enhancement

#478 Add better custom selecting
  Cargo.lock
  czkawka_core/src/common.rs
  czkawka_gui/Cargo.toml
  czkawka_gui/src/connect_popovers.rs
  czkawka_gui/ui/about_dialog.glade
  czkawka_gui/ui/main_window.glade
  czkawka_gui/ui/popover_right_click.glade
  czkawka_gui/ui/popover_select.glade
  czkawka_gui/ui/progress.glade
  czkawka_gui/ui/settings.glade
Labels: enhancement

#480 Don't try to create previews of images that currently are displayed in preview window
  czkawka_gui/src/connect_button_delete.rs
  czkawka_gui/src/connect_button_hardlink.rs
  czkawka_gui/src/connect_button_move.rs
  czkawka_gui/src/gui_data.rs
  czkawka_gui/src/help_functions.rs
  czkawka_gui/src/initialize_gui.rs
Labels: bug

#483 Approximate comparison of music
  czkawka_core/src/same_music.rs
  czkawka_gui/src/connect_button_search.rs
  czkawka_gui/src/gui_main_notebook.rs
  czkawka_gui/ui/main_window.glade
Labels: enhancement

#484 Remove pkgs folder
  .github/workflows/linux.yml
  data/com.github.qarmin.czkawka.desktop
  misc/czkawka-appimage-recipe.yml
Labels: enhancement

#485 Better comparison of music tags
  Changelog.md
  czkawka_core/src/same_music.rs
  czkawka_gui/src/create_tree_view.rs
  czkawka_gui/ui/main_window.glade
Labels: enhancement

#487 Enable sorting for simple treeviews
  czkawka_gui/src/compute_results.rs
  czkawka_gui/src/create_tree_view.rs
  czkawka_gui/src/help_functions.rs
  czkawka_gui/src/initialize_gui.rs
Labels: enhancement

#486 Cache vidoes with serde to avoid forked vid_dup_finder_lib
  Cargo.lock
  czkawka_core/Cargo.toml
  czkawka_core/src/similar_videos.rs
Labels: enhancement

#489 Add confirmation and warning dialog to hard/symlinks
  czkawka_gui/src/connect_button_delete.rs
  czkawka_gui/src/connect_button_hardlink.rs
  czkawka_gui/src/connect_button_move.rs
  czkawka_gui/src/connect_popovers.rs
  czkawka_gui/src/connect_selection_of_directories.rs
  czkawka_gui/src/gui_settings.rs
  czkawka_gui/ui/settings.glade
Labels: enhancement

#490 Multiple small changes
  Cargo.lock
  czkawka_core/Cargo.toml
  czkawka_core/src/similar_videos.rs
  czkawka_gui/src/connect_button_hardlink.rs
  czkawka_gui/src/connect_button_select.rs
  czkawka_gui/src/help_functions.rs
  instructions/Compilation.md
  instructions/Installation.md
  instructions/Instruction.md
Labels: bug, enhancement

#491 Allow to hide upper notebook
  czkawka_gui/src/connect_show_hide_ui.rs
  czkawka_gui/src/gui_bottom_buttons.rs
  czkawka_gui/src/main.rs
  czkawka_gui/ui/main_window.glade
Labels: enhancement

#493 Add button to ignore images with non unique size.
  README.md
  czkawka_core/src/similar_images.rs
  czkawka_gui/src/connect_button_search.rs
  czkawka_gui/src/gui_main_notebook.rs
  czkawka_gui/src/initialize_gui.rs
  czkawka_gui/ui/main_window.glade
Labels: bug, enhancement

#469 Add support for translations
  Cargo.lock
  README.md
  czkawka_core/Cargo.toml
  czkawka_core/i18n.toml
  czkawka_core/src/lib.rs
  czkawka_core/src/localizer.rs
  czkawka_core/src/similar_images.rs
  czkawka_gui/Cargo.toml
  czkawka_gui/i18n.toml
  czkawka_gui/src/compute_results.rs
  czkawka_gui/src/connect_button_delete.rs
  czkawka_gui/src/connect_button_hardlink.rs
  czkawka_gui/src/connect_button_move.rs
  czkawka_gui/src/connect_button_search.rs
  czkawka_gui/src/connect_change_language.rs
  czkawka_gui/src/connect_notebook_tabs.rs
  czkawka_gui/src/connect_popovers.rs
  czkawka_gui/src/connect_progress_window.rs
  czkawka_gui/src/connect_selection_of_directories.rs
  czkawka_gui/src/gui_about.rs
  czkawka_gui/src/gui_bottom_buttons.rs
  czkawka_gui/src/gui_data.rs
  czkawka_gui/src/gui_header.rs
  czkawka_gui/src/gui_main_notebook.rs
  czkawka_gui/src/gui_popovers.rs
  czkawka_gui/src/gui_progress_dialog.rs
  czkawka_gui/src/gui_settings.rs
  czkawka_gui/src/gui_upper_notebook.rs
  czkawka_gui/src/gui_upper_notepad.rs
  czkawka_gui/src/help_functions.rs
  czkawka_gui/src/initialize_gui.rs
  czkawka_gui/src/language_functions.rs
  czkawka_gui/src/main.rs
  czkawka_gui/src/notebook_enums.rs
  czkawka_gui/src/saving_loading.rs
  czkawka_gui/ui/main_window.glade
  czkawka_gui/ui/progress.glade
  czkawka_gui/ui/settings.glade
  i18n.toml
  i18n/en/czkawka_core.ftl
  i18n/en/czkawka_gui.ftl
  i18n/pl/czkawka_core.ftl
  i18n/pl/czkawka_gui.ftl
  instructions/Translations.md
Labels: enhancement

#498 Use translated strings in more places
  czkawka_core/src/similar_images.rs
  czkawka_gui/src/connect_about_buttons.rs
  czkawka_gui/src/connect_button_delete.rs
  czkawka_gui/src/connect_button_hardlink.rs
  czkawka_gui/src/connect_button_move.rs
  czkawka_gui/src/connect_button_save.rs
  czkawka_gui/src/connect_button_search.rs
  czkawka_gui/src/connect_change_language.rs
  czkawka_gui/src/connect_selection_of_directories.rs
  czkawka_gui/src/connect_settings.rs
  czkawka_gui/src/connect_similar_image_size_change.rs
  czkawka_gui/src/help_functions.rs
  czkawka_gui/src/main.rs
  czkawka_gui/src/opening_selecting_records.rs
  i18n/en/czkawka_gui.ftl
  i18n/pl/czkawka_gui.ftl
  instructions/Translations.md
Labels: enhancement

#500 Make UI take less space
  README.md
  czkawka_core/src/duplicate.rs
  czkawka_gui/src/compute_results.rs
  czkawka_gui/src/connect_button_search.rs
  czkawka_gui/src/connect_duplicate_buttons.rs
  czkawka_gui/src/connect_similar_image_size_change.rs
  czkawka_gui/src/gui_main_notebook.rs
  czkawka_gui/src/gui_upper_notebook.rs
  czkawka_gui/src/help_combo_box.rs
  czkawka_gui/src/initialize_gui.rs
  czkawka_gui/src/main.rs
  czkawka_gui/ui/main_window.glade
  i18n/en/czkawka_gui.ftl
  i18n/pl/czkawka_gui.ftl
Labels: enhancement

#501 Better ignore same size files
  czkawka_core/src/similar_images.rs
  czkawka_core/src/similar_videos.rs
  czkawka_gui/src/connect_button_search.rs
Labels: enhancement

#504 Implement threaded search in rest of modes(except empty folders)
  czkawka_core/src/big_file.rs
  czkawka_core/src/broken_files.rs
  czkawka_core/src/common_extensions.rs
  czkawka_core/src/duplicate.rs
  czkawka_core/src/empty_files.rs
  czkawka_core/src/empty_folder.rs
  czkawka_core/src/invalid_symlinks.rs
  czkawka_core/src/same_music.rs
  czkawka_core/src/similar_images.rs
  czkawka_core/src/similar_videos.rs
  czkawka_core/src/temporary.rs
  czkawka_gui/src/connect_button_search.rs
  czkawka_gui/src/gui_progress_dialog.rs
Labels: enhancement

#503 More GTK4 compatibility fixes
  Cargo.lock
  czkawka_core/src/common_extensions.rs
  czkawka_gui/src/connect_button_move.rs
  czkawka_gui/src/connect_button_stop.rs
  czkawka_gui/src/connect_selection_of_directories.rs
  czkawka_gui/src/create_tree_view.rs
  czkawka_gui/src/gui_bottom_buttons.rs
  czkawka_gui/src/gui_main_notebook.rs
  czkawka_gui/src/gui_progress_dialog.rs
  czkawka_gui/src/gui_upper_notebook.rs
  czkawka_gui/src/help_functions.rs
  czkawka_gui/src/initialize_gui.rs
  czkawka_gui/src/main.rs
  czkawka_gui/src/opening_selecting_records.rs
Labels: enhancement

#505 Add more GTK 4 compatibility fixes
  czkawka_gui/src/connect_button_move.rs
  czkawka_gui/src/connect_selection_of_directories.rs
  czkawka_gui/src/gui_bottom_buttons.rs
  czkawka_gui/src/gui_progress_dialog.rs
  czkawka_gui/src/gui_upper_notebook.rs
  czkawka_gui/src/help_functions.rs
  czkawka_gui/src/initialize_gui.rs
  czkawka_gui/src/opening_selecting_records.rs
Labels: enhancement

#506 Use system language when available
  czkawka_cli/src/commands.rs
  czkawka_core/src/big_file.rs
  czkawka_core/src/broken_files.rs
  czkawka_core/src/common.rs
  czkawka_core/src/duplicate.rs
  czkawka_core/src/empty_files.rs
  czkawka_core/src/empty_folder.rs
  czkawka_core/src/invalid_symlinks.rs
  czkawka_core/src/same_music.rs
  czkawka_core/src/similar_images.rs
  czkawka_core/src/similar_videos.rs
  czkawka_core/src/temporary.rs
  czkawka_gui/src/connect_button_move.rs
  czkawka_gui/src/connect_change_language.rs
  czkawka_gui/src/connect_selection_of_directories.rs
  czkawka_gui/src/main.rs
  czkawka_gui/src/opening_selecting_records.rs
  czkawka_gui/src/saving_loading.rs
Labels: enhancement

#507 Improve translations
  czkawka_core/src/big_file.rs
  czkawka_core/src/broken_files.rs
  czkawka_core/src/duplicate.rs
  czkawka_core/src/empty_files.rs
  czkawka_core/src/empty_folder.rs
  czkawka_core/src/invalid_symlinks.rs
  czkawka_core/src/localizer.rs
  czkawka_core/src/same_music.rs
  czkawka_core/src/similar_images.rs
  czkawka_core/src/similar_videos.rs
  czkawka_core/src/temporary.rs
  czkawka_gui/src/compute_results.rs
  czkawka_gui/src/connect_button_delete.rs
  czkawka_gui/src/connect_button_hardlink.rs
  czkawka_gui/src/connect_button_move.rs
  czkawka_gui/src/connect_button_save.rs
  czkawka_gui/src/connect_button_search.rs
  czkawka_gui/src/connect_change_language.rs
  czkawka_gui/src/connect_duplicate_buttons.rs
  czkawka_gui/src/connect_popovers.rs
  czkawka_gui/src/connect_progress_window.rs
  czkawka_gui/src/connect_selection_of_directories.rs
  czkawka_gui/src/connect_settings.rs
  czkawka_gui/src/gui_about.rs
  czkawka_gui/src/gui_bottom_buttons.rs
  czkawka_gui/src/gui_header.rs
  czkawka_gui/src/gui_main_notebook.rs
  czkawka_gui/src/gui_popovers.rs
  czkawka_gui/src/gui_progress_dialog.rs
  czkawka_gui/src/gui_settings.rs
  czkawka_gui/src/gui_upper_notebook.rs
  czkawka_gui/src/help_combo_box.rs
  czkawka_gui/src/initialize_gui.rs
  czkawka_gui/src/opening_selecting_records.rs
  czkawka_gui/src/saving_loading.rs
  czkawka_gui/ui/settings.glade
  i18n/en/czkawka_gui.ftl
  i18n/pl/czkawka_gui.ftl
Labels: enhancement

#510 Update translation and add helpful script
  czkawka_gui/src/gui_about.rs
  czkawka_gui/src/gui_data.rs
  czkawka_gui/src/gui_progress_dialog.rs
  czkawka_gui/src/gui_settings.rs
  czkawka_gui/src/language_functions.rs
  i18n/en/czkawka_gui.ftl
  i18n/pl/czkawka_gui.ftl
  instructions/Translations.md
Labels: bug, enhancement

#508 Add Italian translation - #251
  czkawka_gui/src/language_functions.rs
  i18n/it/czkawka_core.ftl
  i18n/it/czkawka_gui.ftl
  misc/translation_test.py
Labels: enhancement

#514 Show how many files will be deleted/moved
  Changelog.md
  czkawka_gui/src/connect_button_delete.rs
  czkawka_gui/src/connect_button_hardlink.rs
  czkawka_gui/src/connect_button_move.rs
  czkawka_gui/src/connect_popovers.rs
  czkawka_gui/src/help_functions.rs
  czkawka_gui/src/initialize_gui.rs
  czkawka_gui/src/opening_selecting_records.rs
  i18n/en/czkawka_gui.ftl
  i18n/pl/czkawka_gui.ftl
  instructions/Translations.md
Labels: enhancement

#515 Use max line length 180 instead 250
  .rustfmt.toml
  czkawka_cli/src/commands.rs
  czkawka_core/src/big_file.rs
  czkawka_core/src/broken_files.rs
  czkawka_core/src/common.rs
  czkawka_core/src/common_directory.rs
  czkawka_core/src/common_extensions.rs
  czkawka_core/src/common_items.rs
  czkawka_core/src/duplicate.rs
  czkawka_core/src/empty_files.rs
  czkawka_core/src/empty_folder.rs
  czkawka_core/src/invalid_symlinks.rs
  czkawka_core/src/same_music.rs
  czkawka_core/src/similar_images.rs
  czkawka_core/src/similar_videos.rs
  czkawka_core/src/temporary.rs
  czkawka_gui/src/compute_results.rs
  czkawka_gui/src/connect_button_delete.rs
  czkawka_gui/src/connect_button_hardlink.rs
  czkawka_gui/src/connect_button_move.rs
  czkawka_gui/src/connect_button_save.rs
  czkawka_gui/src/connect_button_search.rs
  czkawka_gui/src/connect_notebook_tabs.rs
  czkawka_gui/src/connect_popovers.rs
  czkawka_gui/src/connect_progress_window.rs
  czkawka_gui/src/connect_selection_of_directories.rs
  czkawka_gui/src/connect_settings.rs
  czkawka_gui/src/gui_main_notebook.rs
  czkawka_gui/src/gui_popovers.rs
  czkawka_gui/src/gui_settings.rs
  czkawka_gui/src/gui_upper_notebook.rs
  czkawka_gui/src/help_combo_box.rs
  czkawka_gui/src/initialize_gui.rs
  czkawka_gui/src/language_functions.rs
  czkawka_gui/src/main.rs
  czkawka_gui/src/opening_selecting_records.rs
  czkawka_gui/src/saving_loading.rs
  czkawka_gui/src/taskbar_progress_win.rs
Labels: enhancement

#516 Add reference folder
  Changelog.md
  README.md
  czkawka_core/src/big_file.rs
  czkawka_core/src/broken_files.rs
  czkawka_core/src/common_directory.rs
  czkawka_core/src/common_messages.rs
  czkawka_core/src/duplicate.rs
  czkawka_core/src/empty_files.rs
  czkawka_core/src/invalid_symlinks.rs
  czkawka_core/src/same_music.rs
  czkawka_core/src/similar_images.rs
  czkawka_core/src/similar_videos.rs
  czkawka_core/src/temporary.rs
  czkawka_gui/src/compute_results.rs
  czkawka_gui/src/connect_button_delete.rs
  czkawka_gui/src/connect_button_hardlink.rs
  czkawka_gui/src/connect_button_move.rs
  czkawka_gui/src/connect_button_search.rs
  czkawka_gui/src/connect_change_language.rs
  czkawka_gui/src/connect_duplicate_buttons.rs
  czkawka_gui/src/connect_selection_of_directories.rs
  czkawka_gui/src/create_tree_view.rs
  czkawka_gui/src/gui_main_notebook.rs
  czkawka_gui/src/gui_upper_notebook.rs
  czkawka_gui/src/help_functions.rs
  czkawka_gui/src/initialize_gui.rs
  czkawka_gui/src/opening_selecting_records.rs
  czkawka_gui/src/saving_loading.rs
  i18n/en/czkawka_gui.ftl
  i18n/pl/czkawka_gui.ftl
Labels: enhancement

#524 Reorganize saving/loading data from file
  czkawka_gui/src/saving_loading.rs
Labels: enhancement

#525 Add new step to check progress of comparing images.
  czkawka_core/src/broken_files.rs
  czkawka_core/src/similar_images.rs
  czkawka_gui/src/connect_progress_window.rs
  czkawka_gui/src/initialize_gui.rs
  czkawka_gui/src/saving_loading.rs
  i18n/en/czkawka_gui.ftl
Labels: bug, enhancement

#526 Translation button
  czkawka_gui/src/connect_about_buttons.rs
  czkawka_gui/src/gui_about.rs
  czkawka_gui/src/help_combo_box.rs
  czkawka_gui/ui/about_dialog.glade
  i18n/de/czkawka_gui.ftl
  i18n/en/czkawka_gui.ftl
  i18n/it/czkawka_gui.ftl
  i18n/pl/czkawka_gui.ftl
Labels: bug

#527 Don't crash when adding excluded directories
  czkawka_gui/src/connect_selection_of_directories.rs
Labels: bug

#529 Faster image compare option
  czkawka_core/src/similar_images.rs
  czkawka_gui/src/connect_button_search.rs
  czkawka_gui/src/gui_main_notebook.rs
  czkawka_gui/ui/main_window.glade
  i18n/en/czkawka_gui.ftl
Labels: enhancement

#530 Handle image crashes
  Cargo.toml
  czkawka_core/src/broken_files.rs
  czkawka_core/src/duplicate.rs
  czkawka_core/src/similar_images.rs
Labels: bug

#532 [WIP] Add raw images support
  Cargo.lock
  Changelog.md
  czkawka_core/Cargo.toml
  czkawka_core/src/broken_files.rs
  czkawka_core/src/common.rs
  czkawka_core/src/common_extensions.rs
  czkawka_core/src/same_music.rs
  czkawka_core/src/similar_images.rs
  czkawka_core/src/similar_videos.rs
  czkawka_gui/src/initialize_gui.rs
  instructions/Compilation.md
  instructions/Installation.md
  snap/snapcraft.yaml
Labels: help wanted

#534 Add Portuguese translation
  czkawka_gui/src/language_functions.rs
  i18n/de/czkawka_gui.ftl
  i18n/it/czkawka_gui.ftl
  i18n/pl/czkawka_gui.ftl
  i18n/pt/czkawka_core.ftl
  i18n/pt/czkawka_gui.ftl
Labels: enhancement
