Repository qarmin/czkawka, pull requests merged in 2021-01, with the labels that each got.

#179 Use master gtk plugin again
  .github/workflows/linux.yml
  czkawka_core/src/common_items.rs
  czkawka_gui/src/double_click_opening.rs
  czkawka_gui/src/initialize_gui.rs
  czkawka_gui/src/saving_loading.rs
Labels: enhancement

#183 Only show preview when 1 image is selected
  czkawka_gui/src/gui_data.rs
  czkawka_gui/src/initialize_gui.rs
Labels: bug

#184 Simplify a little code
  czkawka_gui/src/connect_button_delete.rs
  czkawka_gui/src/connect_popovers.rs
  czkawka_gui/src/connect_selection_of_directories.rs
  czkawka_gui/src/help_functions.rs
Labels: enhancement

#185 Remove some debug variables
  czkawka_core/src/big_file.rs
  czkawka_core/src/duplicate.rs
  czkawka_core/src/empty_files.rs
  czkawka_core/src/empty_folder.rs
  czkawka_core/src/invalid_symlinks.rs
  czkawka_core/src/same_music.rs
  czkawka_core/src/similar_images.rs
  czkawka_core/src/temporary.rs
  czkawka_core/src/zeroed.rs
Labels: enhancement

#186 Add buffered write/read
  czkawka_core/src/big_file.rs
  czkawka_core/src/duplicate.rs
  czkawka_core/src/empty_files.rs
  czkawka_core/src/empty_folder.rs
  czkawka_core/src/invalid_symlinks.rs
  czkawka_core/src/same_music.rs
  czkawka_core/src/similar_images.rs
  czkawka_core/src/temporary.rs
  czkawka_core/src/zeroed.rs
Labels: enhancement

#189 Modernize notebook handling
  czkawka_gui/src/connect_button_delete.rs
  czkawka_gui/src/connect_button_save.rs
  czkawka_gui/src/connect_button_search.rs
  czkawka_gui/src/connect_button_select.rs
  czkawka_gui/src/connect_button_symlink.rs
  czkawka_gui/src/connect_compute_results.rs
  czkawka_gui/src/connect_notebook_tabs.rs
  czkawka_gui/src/connect_popovers.rs
  czkawka_gui/src/gui_data.rs
  czkawka_gui/src/help_functions.rs
  czkawka_gui/src/main.rs
  czkawka_gui/src/notebook_enums.rs
Labels: enhancement

#190 Use directly TreeView instead ScrolledWindow->TreeView
  czkawka_gui/czkawka.glade
  czkawka_gui/src/connect_button_delete.rs
  czkawka_gui/src/connect_button_search.rs
  czkawka_gui/src/connect_button_symlink.rs
  czkawka_gui/src/connect_compute_results.rs
  czkawka_gui/src/connect_popovers.rs
  czkawka_gui/src/connect_selection_of_directories.rs
  czkawka_gui/src/gui_data.rs
  czkawka_gui/src/gui_main_notebook.rs
  czkawka_gui/src/help_functions.rs
  czkawka_gui/src/initialize_gui.rs
  czkawka_gui/src/main.rs
  czkawka_gui/src/saving_loading.rs
Labels: enhancement

#194 Split Gui code into multiple files
  czkawka_gui/src/connect_button_delete.rs
  czkawka_gui/src/connect_button_save.rs
  czkawka_gui/src/connect_button_search.rs
  czkawka_gui/src/connect_button_select.rs
  czkawka_gui/src/connect_button_stop.rs
  czkawka_gui/src/connect_button_symlink.rs
  czkawka_gui/src/connect_compute_results.rs
  czkawka_gui/src/connect_hide_text_view_errors.rs
  czkawka_gui/src/connect_notebook_tabs.rs
  czkawka_gui/src/connect_popovers.rs
  czkawka_gui/src/connect_progress_window.rs
  czkawka_gui/src/connect_selection_of_directories.rs
  czkawka_gui/src/connect_settings.rs
  czkawka_gui/src/gui_bottom_buttons.rs
  czkawka_gui/src/gui_data.rs
  czkawka_gui/src/gui_main_notebook.rs
  czkawka_gui/src/gui_popovers.rs
  czkawka_gui/src/gui_progress_dialog.rs
  czkawka_gui/src/gui_upper_notepad.rs
  czkawka_gui/src/initialize_gui.rs
  czkawka_gui/src/main.rs
  czkawka_gui/src/saving_loading.rs
Labels: enhancement

#195 Fix included/excluded files which contains commas
  czkawka_cli/src/commands.rs
  czkawka_cli/src/main.rs
  czkawka_core/src/big_file.rs
  czkawka_core/src/common_directory.rs
  czkawka_core/src/common_items.rs
  czkawka_core/src/duplicate.rs
  czkawka_core/src/empty_files.rs
  czkawka_core/src/empty_folder.rs
  czkawka_core/src/invalid_symlinks.rs
  czkawka_core/src/same_music.rs
  czkawka_core/src/similar_images.rs
  czkawka_core/src/temporary.rs
  czkawka_core/src/zeroed.rs
  czkawka_gui/src/connect_button_search.rs
  czkawka_gui/src/help_functions.rs
Labels: bug

#197 Move image cache to cache from config dir
  czkawka_core/src/similar_images.rs
  czkawka_gui/src/saving_loading.rs
  instructions/Instruction.md
Labels: enhancement

#199 Fix error when closing dialog progress by X
  czkawka_gui/src/connect_button_search.rs
Labels: bug

#200 Remove save workaround and fix crashes
  czkawka_core/src/similar_images.rs
Labels: bug, enhancement

#202 Add broken files support
  README.md
  czkawka_cli/src/commands.rs
  czkawka_cli/src/main.rs
  czkawka_core/src/broken_files.rs
  czkawka_core/src/lib.rs
  czkawka_core/src/similar_images.rs
  czkawka_gui/czkawka.glade
  czkawka_gui/src/connect_button_delete.rs
  czkawka_gui/src/connect_button_save.rs
  czkawka_gui/src/connect_button_search.rs
  czkawka_gui/src/connect_button_select.rs
  czkawka_gui/src/connect_compute_results.rs
  czkawka_gui/src/connect_popovers.rs
  czkawka_gui/src/connect_progress_window.rs
  czkawka_gui/src/create_tree_view.rs
  czkawka_gui/src/double_click_opening.rs
  czkawka_gui/src/gui_data.rs
  czkawka_gui/src/gui_main_notebook.rs
  czkawka_gui/src/help_functions.rs
  czkawka_gui/src/initialize_gui.rs
  czkawka_gui/src/main.rs
  czkawka_gui/src/notebook_enums.rs
  instructions/Instruction.md
Labels: enhancement

#204 Add cache for broken files
  czkawka_cli/src/commands.rs
  czkawka_core/src/broken_files.rs
  czkawka_core/src/common_extensions.rs
  czkawka_core/src/similar_images.rs
  instructions/Instruction.md
Labels: enhancement

#205 Add cache for duplicate
  README.md
  czkawka_core/src/duplicate.rs
  czkawka_core/src/similar_images.rs
  instructions/Instruction.md
Labels: enhancement

#206 Use the oldest available OS in Linux and Mac CI and the newest on Windows
  .github/workflows/linux.yml
  .github/workflows/mac.yml
  .github/workflows/windows.yml
Labels: enhancement

#209 Add missing popover info for invalid symlinks
  czkawka_gui/src/connect_popovers.rs
Labels: bug

#211 Sort Results by path where it is possible
  czkawka_gui/src/connect_compute_results.rs
Labels: enhancement

#210 Add support for finding broken zip and audio files
  .github/workflows/linux.yml
  .github/workflows/quality.yml
  Cargo.lock
  README.md
  czkawka_core/Cargo.toml
  czkawka_core/src/broken_files.rs
  instructions/Instruction.md
Labels: enhancement

#212 Decrease ram usage
  czkawka_core/src/broken_files.rs
  czkawka_core/src/duplicate.rs
  czkawka_core/src/same_music.rs
  czkawka_core/src/similar_images.rs
  czkawka_core/src/zeroed.rs
Labels: enhancement

#203 Add Flatpak support
  flatpak/cargo-sources.json
  flatpak/com.github.qarmin.Czkawka.metainfo.xml
  flatpak/com.github.qarmin.Czkawka.yaml
Labels: enhancement

#223 Add support for moving selection by keyboard to update similar image preview
  czkawka_gui/src/initialize_gui.rs
Labels: enhancement

#226 Add about dialog
  czkawka_core/src/duplicate.rs
  czkawka_gui/czkawka.glade
  czkawka_gui/src/connect_about_buttons.rs
  czkawka_gui/src/connect_header_buttons.rs
  czkawka_gui/src/gui_about.rs
  czkawka_gui/src/gui_data.rs
  czkawka_gui/src/gui_header.rs
  czkawka_gui/src/gui_options.rs
  czkawka_gui/src/initialize_gui.rs
  czkawka_gui/src/main.rs
Labels: enhancement

#227 Remove checking for ico in similar images
  czkawka_core/src/broken_files.rs
  czkawka_core/src/similar_images.rs
  instructions/Instruction.md
Labels: enhancement

#229 Change progress dialog to progress window
  czkawka_gui/czkawka.glade
  czkawka_gui/src/connect_button_search.rs
  czkawka_gui/src/connect_button_stop.rs
  czkawka_gui/src/connect_compute_results.rs
  czkawka_gui/src/connect_progress_window.rs
  czkawka_gui/src/gui_data.rs
  czkawka_gui/src/gui_progress_dialog.rs
  czkawka_gui/src/initialize_gui.rs
Labels: enhancement
