Repository qarmin/czkawka, pull requests merged in 2022-08, with the labels that each got.

#796 Added Korean localization to GUI
  czkawka_gui/i18n/ko/czkawka_gui.ftl
Labels: enhancement

#797 Added korean language to GUI
  czkawka_core/i18n/cs/czkawka_core.ftl
  czkawka_core/i18n/ko/czkawka_core.ftl
  czkawka_gui/i18n/cs/czkawka_gui.ftl
  czkawka_gui/i18n/de/czkawka_gui.ftl
  czkawka_gui/i18n/es/czkawka_gui.ftl
  czkawka_gui/i18n/fr/czkawka_gui.ftl
  czkawka_gui/i18n/it/czkawka_gui.ftl
  czkawka_gui/i18n/ja/czkawka_gui.ftl
  czkawka_gui/i18n/ko/czkawka_gui.ftl
  czkawka_gui/i18n/no/czkawka_gui.ftl
  czkawka_gui/i18n/pl/czkawka_gui.ftl
  czkawka_gui/i18n/pt/czkawka_gui.ftl
  czkawka_gui/i18n/ru/czkawka_gui.ftl
  czkawka_gui/i18n/sv/czkawka_gui.ftl
  czkawka_gui/i18n/tr/czkawka_gui.ftl
  czkawka_gui/i18n/uk/czkawka_gui.ftl
  czkawka_gui/i18n/zh/czkawka_gui.ftl
  czkawka_gui/src/language_functions.rs
Labels: enhancement

#815 Update dependencies and fix clippy warnings
  Cargo.lock
  czkawka_cli/Cargo.toml
  czkawka_core/Cargo.toml
  czkawka_core/src/broken_files.rs
  czkawka_core/src/similar_images.rs
  czkawka_gui/Cargo.toml
Labels: bug, enhancement

#799 Attempt to fix similar images algorithm
  Cargo.lock
  czkawka_core/src/similar_images.rs
Labels: bug
